version: '3.8'
services:
 
  neo4j:
    container_name: neo4j
    restart: always
    image: "neo4j:latest"
    environment:
      - "NEO4J_AUTH=neo4j/your_password"
      - 'NEO4J_PLUGINS=["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - db_network
      - web_network
    volumes:
     - ./neo4japoc/plugins:/plugins
     - ./neo4japoc/conf:/conf
     - ./neo4japoc/scripts:/var/lib/neo4j/import/scripts
  
  threatcopilot:
    container_name: threatcopilot
    build: .
    ports:
      - "5005:5005"
    networks:
      - db_network
      - web_network

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - threatcopilot
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
    
    
