MATCH (n:Vocabulary) DETACH DELETE(n);
MATCH (n:StoreVocabulary) DETACH DELETE(n);
MATCH (n:DataFlowVocabulary) DETACH DELETE(n);
MATCH (n:InteractorVocabulary) DETACH DELETE(n);
MATCH (n:ProcessVocabulary) DETACH DELETE(n);
MATCH (n:StoreTerm) DETACH DELETE(n);
MATCH (n:DataFlowTerm) DETACH DELETE(n);
MATCH (n:InteractorTerm) DETACH DELETE(n);
MATCH (n:ProcessTerm) DETACH DELETE(n);
